name: Keep Streamlit App Awake

on:
  schedule:
    # Runs every 10 minutes
    - cron: "*/10 * * * *"

  # Allows manual execution from GitHub
  workflow_dispatch:

jobs:
  keep-awake:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Streamlit app
        run: |
          curl -L --fail --silent --show-error \
            --max-time 30 \
            "https://industrial-workplace-safetydetection.streamlit.app"
